#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCHjqDjZ1nNaypMBKRYoG+DhpSWxNLtlOjecbFkZxqLFZUGtmgUixe7Fm5iLs8FjTe/haOPGHLq17FHTgwmiMxidqcZ1I/jkpQJLEdnQK/buGd/t9wVdfqX72grmLUPP+00Upk8XaawLWw9oKCDGHUd5OkAzsWv6FRKIDsc/qSQ4VmGbhLACj+1y7X+RGZNRnHR4s3RPNOGBTa5ZkXBWnuEnqUV15GtrP9aRpjgWWjWtB+LIVY38j3LKb/km4E1UOwXA4bXXydGiyIMBqvU8zkCNu8end4YdjbLyWAIi7sfb8TFIk0wahPdW9doTApy9PoWDD8D6oxIbyjJDjSwNfC9  
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD           
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
